### ISSUE TITLE
Issues with custom unmarshal function

### ISSUE THREAD

**Issue by icyphox** [adrg/frontmatter#1]
Hey, thank you for this great package, I'm currently using it in my [static site generator](https://github.com/icyphox/go-vite). I'm having issues defining a custom unmarshal function. I'm trying to parse frontmatter to grab an ISO8601 date, convert it into a `time.Time`, and marshal it into my structure.

Here's what I've got so far:

```go
package main

import (
	"bytes"
	"fmt"
	"github.com/adrg/frontmatter"
	"gopkg.in/yaml.v2"
	"time"
)

type Matter struct {
	Template string    `yaml:"template"`
	URL      string    `yaml:"url"`
	Title    string    `yaml:"title"`
	Subtitle string    `yaml:"subtitle"`
	Date     time.Time `yaml:"date"`
	Body     string
}

func (m *Matter) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var temp struct {
		Template string `yaml:"template"`
		URL      string `yaml:"url"`
		Title    string `yaml:"title"`
		Subtitle string `yaml:"subtitle"`
		Date     string `yaml:"date"`
		Body     string
	}

	if err := unmarshal(&temp); err != nil {
		return err
	}

	layout := "2006-01-02"
	var date8601 time.Time
	var err error
	if temp.Date != "" {
		date8601, err = time.Parse(layout, temp.Date)
		if err != nil {
			return err
		}
	}

	m = &Matter{
		Template: temp.Template,
		URL:      temp.URL,
		Title:    temp.Title,
		Subtitle: temp.Subtitle,
		Date:     date8601,
		Body:     temp.Body,
	}
        fmt.Println(m)  // The full object gets printed!
	return nil
}

var format = frontmatter.NewFormat("---", "---", yaml.Unmarshal)

// Parses frontmatter, populates the `matter` struct and
// returns the rest
func parseFrontmatter(inputBytes []byte) ([]byte, Matter) {
	m := Matter{}
	input := bytes.NewReader(inputBytes)
	rest, err := frontmatter.Parse(input, &m, format)
	fmt.Println(m)    // Empty object

	if err != nil {
		printErr(err)
	}
	return rest, m
}
```
Ideally, this should populate the `m` object, and it seems to do so when I print it from within `UnmarshalYAML()`, but when I print it in my `parseFrontmatter` function, it's empty. Any ideas? 

Excuse the bad quality of code—I'm only a few days into the language. :)

**Comment by adrg** [comment]
Hi @icyphox. Can you attach the input you are trying to parse as well? Also, is there an error reported?

**Comment by adrg** [comment]
If I had to guess:
```
m = &Matter{
    Template: temp.Template,
    URL:      temp.URL,
    Title:    temp.Title,
    Subtitle: temp.Subtitle,
    Date:     date8601,
    Body:     temp.Body,
}
```
should be:
```
*m = Matter{
	Template: temp.Template,
	URL:      temp.URL,
	Title:    temp.Title,
	Subtitle: temp.Subtitle,
	Date:     date8601,
	Body:     temp.Body,
}
```
That's because you actually want to change the value of the receiver of your `UnmarshalYAML` method.

Also, there's no need to create a custom format for this as `---`, `----` is already supported by default for YAML.

**Comment by adrg** [comment]
Design-wise, you can also define the `Date` field to be a custom struct, having a custom `UnmarshalYAML` method. That way, you don't need to have a custom `UnmarshalYAML` method on your `Matter` struct just for the date. Furthermore, you can use the new date type (which has all the methods of `time.Time`, because it embeds it) in other structs as well, if you need to do so.

```go
package main

import (
	"bytes"
	"fmt"
	"log"
	"time"

	"github.com/adrg/frontmatter"
)

var layout = "2006-01-02"

type Date8601 struct {
	time.Time
}

func (d *Date8601) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var date string

	err := unmarshal(&date)
	if err != nil {
		return err
	}

	d.Time, err = time.Parse(layout, date)
	return err
}

type Matter struct {
	Template string   `yaml:"template"`
	URL      string   `yaml:"url"`
	Title    string   `yaml:"title"`
	Subtitle string   `yaml:"subtitle"`
	Date     Date8601 `yaml:"date"`
	Body     string
}

func parseFrontmatter(b []byte) (*Matter, []byte, error) {
	m := &Matter{}
	rest, err := frontmatter.Parse(bytes.NewReader(b), m)
	return m, rest, err
}

func main() {
	input := []byte(`---
template: "some template"
url: "https://example.com"
title: "some title"
subtitle: "some subtitle"
date: "2020-11-03"
---
rest of the content`)

	m, rest, err := parseFrontmatter(input)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%v\n", m)
	fmt.Println(string(rest))
}
```

**Comment by icyphox** [comment]
> should be:

> *m = Matter{
>	Template: temp.Template,
>	URL:      temp.URL,
>	Title:    temp.Title,
>	Subtitle: temp.Subtitle,
>	Date:     date8601,
>	Body:     temp.Body,
>}

Oh yeah how’d I miss that haha. 

> Design-wise, you can also define the Date field to be a custom struct, having a custom UnmarshalYAML method. That way, you don't need to have a custom UnmarshalYAML method on your Matter struct just for the date. Furthermore, you can use the new date type (which has all the methods of time.Time, because it embeds it) in other structs as well, if you need to do so.

That's neat, I hadn't thought of that! Thanks!

> Also, there's no need to create a custom format for this as ---, --- is already supported by default for YAML.

Ah of course, since `frontmatter.Parse()` calls `yaml.Unmarshal()` anyway.

Great, thanks a ton! I’ll close this now.

**Comment by adrg** [comment]
No problem. Glad to help.
