### ISSUE TITLE
Parse nested TOML

### ISSUE THREAD

**Issue by pinpox** [adrg/frontmatter#29]
I'm trying to parse the frontmatter as used by the [zola static site generator](https://www.getzola.org/), it looks something like this for my blog:

```
++
draft = true
date = 2020-07-17T09:30:09+02:00
title = "Test example of new style"
description = "This is the new example used to test out typography settings" 
slug = "test-example" 

[taxonomies]
tags = ["github", "markdown", "golang", "CI", "CD", "automation"]
+++
```

It works for the most part, but fails to get the tags, I assume because they are nested below the `[taxonomis]` subdivision. Is there a way to parse these? I'm using the example code from the readme, but it only works for the other fields.

Thanks for any help!

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if necessary.

**Comment by pinpox** [comment]
Thank you, workse perfectly!
